export const ACCESS_TOKEN_EXPIRES_IN_SECONDS = 900
export const TOKEN_TIMESTAMP_TOLERANCE_SECONDS = 300
export const HEARTBEAT_STALE_THRESHOLD_SECONDS = 1920
export const HEARTBEAT_RECOMMENDED_SECONDS = 1800

export const PROVISIONING_REQUIRED_SIGNALS = 10
export const PROVISIONING_MINIMUM_SUCCESS_SIGNALS = 8
export const PROVISIONING_INTERVAL_SECONDS = 5
export const PROVISIONING_EXPIRES_IN_SECONDS = 60

export const MINUTE_WINDOW_TOLERANCE_SECONDS = 60

export const RECOVERY_CODE_COUNT = 8
export const RECOVERY_CODE_LENGTH = 16
